version: "3"
services:
    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '8082:80'

    server:
        build: 
            context: ./Server/
            dockerfile: Dockerfile
        image: server
        ports: 
<<<<<<< HEAD
            - 8080:8080
        networks: 
            - app-network
        links:
            - db
=======
            - 8081:8081
        networks: 
            - app-network
>>>>>>> Finish to create the certificat and the part of nginx on docker

    mobile_client:
        build:
            context: ./Mobile/
            dockerfile: Dockerfile
        image: mobile
        depends_on: 
            - server
            - nginx

    webapp:
        build: 
            context: ./web_app/
            dockerfile: Dockerfile
        image: web_client
        ports: 
            - 8081:8081
        depends_on: 
            - mobile_client
            - server

    db:
        image: "mongo"
        ports:
            - "27017:27017"

networks:
    app-network:
        driver: bridge
