version: "3"
services:
    api:
        build: 
            context: ./server
            dockerfile: Dockerfile
        image: api
        ports: 
            - 8080:8080
        networks: 
            - app-network
        links:
            - db

    mobile_client:
        build:
            context: ./Mobile/
            dockerfile: Dockerfile
        image: mobile
        depends_on: 
            - api

    webapp:
        build: 
            context: ./web_app/
            dockerfile: Dockerfile
        image: web_client
        ports: 
            - 8081:8081
        depends_on: 
            - mobile_client
            - api
        volumes: 
            - /app/node_modules
            - ./web_app:/app
            - apk:/var/www/:ro
            
    db:
        image: "mongo"
        ports:
            - "27017:27017"

volumes:
    apk:

networks:
    app-network:
        driver: bridge