version: "3"
services:
    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '8082:80'

    server:
        build: 
            context: ./Server/
            dockerfile: Dockerfile
        image: server
        ports: 
            - 8081:8081
        networks: 
            - app-network

    mobile_client:
        build:
            context: ./Mobile/
            dockerfile: Dockerfile
        image: mobile
        depends_on: 
            - server
            - nginx

    webapp:
        build: 
            context: ./web_app/
            dockerfile: Dockerfile
        image: web_client
        ports: 
            - 8080:8080
        depends_on: 
            - mobile_client
            - server

networks:
    app-network:
        driver: bridge